### ISSUE TITLE
The official document refer to use 'google-github-actions/ssh-compute@v0' but the release tag don't exist

### ISSUE THREAD

**Issue by cl8dep** [google-github-actions/ssh-compute#13]
### TL;DR

I am using the action and the tag v0 don't exist in the repo.

### Action YAML

```yaml
- id: "compute-ssh"
        uses: "google-github-actions/ssh-compute@v0"
        with:
          instance_name: "sil-qa-dev"
          zone: "us-east1-b"
          ssh_private_key: ${{ secrets.DEV_SSH_KEY }}
          command: |
            whoami
```
