### ISSUE TITLE
 Error: google-github-actions/ssh-compute failed with: error:0909006C:PEM routines:get_name:no start line

### ISSUE THREAD

**Issue by miss8549** [google-github-actions/ssh-compute#42]
### TL;DR

I don't know if it's my sshkey problem or GCP serviceaccounts json problem

sorry english is not my mother tongue thank you

### Observed behavior

Error: google-github-actions/ssh-compute failed with: error:0909006C:PEM routines:get_name:no start line

### Action YAML

```yaml
name: deploy
on:
  push:
    branches:
      - cicd-test
jobs:
  gitpull:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v3

    - id: auth
      uses: google-github-actions/auth@v0
      with:
        credentials_json: ${{ secrets.GCP_CREDENTIALS }}

    - id: compute-ssh
      uses: google-github-actions/ssh-compute@v0
      with:
        instance_name: ***
        user: ${{ secrets.SSH_USER }}
        zone: ***
        ssh_private_key: ${{ secrets.TEST_SSH_PPK_KEY }}
        script: |
          cd /some/path
          pwd

    - id: 'stdmsg'
      run: |-
        echo '${{ steps.compute-ssh.outputs.stdout }}'
        echo '${{ steps.compute-ssh.outputs.stderr }}'
```

### Log output

```text
Run google-github-actions/ssh-compute@v0
  with:
    instance_name: ***
    user: ***
    zone: asia-east1-a
    ssh_private_key: ***
  
    script: cd /some/path
  pwd
  
  env:
    CLOUDSDK_AUTH_CREDENTIAL_FILE_OVERRIDE: jsonfile
    GOOGLE_APPLICATION_CREDENTIALS: jsonfile
    GOOGLE_GHA_CREDS_PATH: jsonfile
    CLOUDSDK_CORE_PROJECT: projectname
    CLOUDSDK_PROJECT: projectname
    GCLOUD_PROJECT: projectname
    GCP_PROJECT: projectname
    GOOGLE_CLOUD_PROJECT: projectname
Error: google-github-actions/ssh-compute failed with: error:0909006C:PEM routines:get_name:no start line
```
