### ISSUE TITLE
Permission \'iam.serviceAccounts.getAccessToken\' denied on resource (or it may not exist).

### ISSUE THREAD

**Issue by durgesh-sahani** [google-github-actions/ssh-compute#60]
### TL;DR

google-github-actions/ssh-compute failed with: failed to execute gcloud command `gcloud compute ssh *** --zone *** --ssh-key-file /tmp/4de5e605663603be1a4b13fa/google_compute_engine --quiet --tunnel-through-iap --project *** --command echo Hello world`: ERROR: (gcloud.compute.ssh) There was a problem refreshing your current auth tokens: Unable to acquire impersonated credentials

{
  "error": {
    "code": 403,
    "message": "Permission \'iam.serviceAccounts.getAccessToken\' denied on resource (or it may not exist).",
    "status": "PERMISSION_DENIED",
    "details": [
      {
        "@type": "type.googleapis.com/google.rpc.ErrorInfo",
        "reason": "IAM_PERMISSION_DENIED",
        "domain": "iam.googleapis.com",
        "metadata": {
          "permission": "iam.serviceAccounts.getAccessToken"
        }
      }
    ]
  }
}

### Action YAML

```yaml
name: Deploy PHP to Compute Engine

on:
  push:
    branches:
      - test
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  deploy:
    # Add 'id-token' with the intended permissions for workload identity federation
    permissions:
      contents: 'read'
      id-token: 'write'
      
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v1'
        with:
          workload_identity_provider: '${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}'
          service_account: '${{ secrets.GCP_SERVICE_ACCOUNT }}'

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'

      - name: Install dependencies
        run: composer install

      - id: 'compute-ssh'
        name: Deploy to Compute Engine
        uses: 'google-github-actions/ssh-compute@v0'
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          zone: ${{ secrets.GCP_ZONE }}
          ssh_private_key: ${{ secrets.GCP_SSH_PRIVATE_KEY }}
          instance_name: ${{ secrets.GCP_INSTANCE_NAME }}
          command: 'echo Hello world'
```
