### ISSUE TITLE
Question! Deploy PHP Code on Google Compute Engine. Why /home/runner/work is empty?

### ISSUE THREAD

**Issue by durgesh-sahani** [google-github-actions/ssh-compute#61]
Hello There,

Can anyone help me to understand why I'm not seeing the code under /home/runner/work?

I have PHP code which I want to deploy on Google Compute Engine!

Here is my workflow file:

```
on:
  push:
    branches: [ "test" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v1'
        with:
          workload_identity_provider: '${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}'
          service_account: '${{ secrets.GCP_SERVICE_ACCOUNT }}'

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'

      - name: Install dependencies
        run: composer install

      - id: 'compute-ssh'
        name: Deploy to Compute Engine
        uses: 'google-github-actions/ssh-compute@v0'
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          zone: ${{ secrets.GCP_ZONE }}
          ssh_private_key: ${{ secrets.GCP_SSH_PRIVATE_KEY }}
          instance_name: ${{ secrets.GCP_INSTANCE_NAME }}
          command: echo "Code Deployed!"

      - id: 'output'
        run: |-
          echo '${{ steps.compute-ssh.outputs.stdout }}'
          echo '${{ steps.compute-ssh.outputs.stderr }}'
```

Even I tried this but no luck
```
command: |-
cd /var/www/test
git pull origin test
```
I checked the log auth and ssh are successful, there is no error.
Help me to correct above file to deployed the code on compute engine.

Thanks,
