### ISSUE TITLE
Direct Workload Identity Federation

### ISSUE THREAD

**Issue by Naramsim** [google-github-actions/ssh-compute#66]
### TL;DR

Hi, does this project support Direct Workload Identity Federation?

https://github.com/google-github-actions/auth#preferred-direct-workload-identity-federation

Without specifying a Service Account?

I tried and failed with 

```log
ERROR: (gcloud.compute.ssh) Could not add SSH key to instance metadata:
 - The user does not have access to service account 'XXX-compute@developer.gserviceaccount.com'.  User: 'repo:PokeAPI/deploy:ref:refs/heads/gql (projects/XXX/locations/global/workloadIdentityPools/github)'.  Ask a project owner to grant you the iam.serviceAccountUser role on the service account
```

PS: I also added the public SSH key to my instance but the Github Action still cannot connect.

### Action YAML

```yaml
name: update-gql-data
on:
  push:
    branches:
      - gql
jobs:
  update-gql-data:
    runs-on: ubuntu-22.04
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
    - uses: 'actions/checkout@v4'
    - uses: 'google-github-actions/auth@v2'
      with:
        project_id: 'pokeapi-215911'
        workload_identity_provider: 'projects/XXX/locations/global/workloadIdentityPools/github/providers/deploy'
    - uses: 'google-github-actions/ssh-compute@v1'
      with:
        instance_name: 'graphql5'
        zone: 'us-east1-b'
        ssh_private_key: '${{ secrets.GCP_SSH_PRIVATE_KEY }}'
        user: ga
        command: |-
          sudo -i
          (cd pokeapi && ls)
    - run: |-
        echo '${{ steps.compute-ssh.outputs.stdout }}'
        echo '${{ steps.compute-ssh.outputs.stderr }}'
```
